### ISSUE TITLE
请问根据预设生成的模板Word文件在哪里保存呢？

### ISSUE THREAD

**Issue by hjtgh** [greyovo/md2word-pandoc#5]
我自己根据pandoc导出的模板文件进行修改样式，然后用这个模板文件来导出时一直不生效，所以想看一下这个生成的模板文件，放到typora里面用😂
![image](https://user-images.githubusercontent.com/61310881/145746953-6cce0fb2-4d65-4c94-8853-d7da0c2d82a7.png)
 reference一直不生效

**Comment by greyovo** [comment]
> 我自己根据pandoc导出的模板文件进行修改样式，然后用这个模板文件来导出时一直不生效，所以想看一下这个生成的模板文件，放到typora里面用😂
> 
> ![image](https://user-images.githubusercontent.com/61310881/145746953-6cce0fb2-4d65-4c94-8853-d7da0c2d82a7.png)
> 
>  reference一直不生效

应该是放在了软件运行目录下的 ".\temp\ref.docx"

**Comment by hjtgh** [comment]
这个文件会在转换成功后被重置😥，依然不是模版文件。

**Comment by greyovo** [comment]
> 这个文件会在转换成功后被重置😥，依然不是模版文件。

😂啊 好久之前写的程序现在都忘了 你可以试试随便用一个md文件导出的docx文件作为reference的docx试试，毕竟本质都只是参考其中的样式而已，内容不重要

**Comment by hjtgh** [comment]
😂都试过了，都不生效。不过我看了下源码，找到了一行似乎是重置文件的代码（不太懂c#😂）。我再研究研究，实在不行就直接用这个软件了，这个软件设置格式也确实方便😁
